
services:
  api01: &api
    #image: rinha-de-backend-2024-q1:latest
    build:
      context: .
      #platform: linux/amd64
    environment:
      - DB_HOSTNAME=db
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"
    
  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - 8082:8080

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "60MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./scripts/dml.sql:/docker-entrypoint-initdb.d/dml.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "1.15"
          memory: "390MB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rinha -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

